test;
[RemoveExceptions]
    class Test {
    void foo() {
    }
  }
